cvm-version: 0.13.0
cpus: 2
memory: 2048

# Measured into the enclave attestation.
keyserver-url: https://keys.tanyaverma.sh:9443

networks:
  web:

containers:
  - name: "demo"
    image: "ghcr.io/tinfoilsh/confidential-secrets-demo@sha256:3548fe5b23c9dd780061d1d579fea11232f1fff993f5cd211dc392ed52216656" # v0.0.5
    restart: always
    networks: [web]
    secrets:
      - DEMO_SECRET

shim:
  listen-port: 443
  upstream-port: 8080
  paths:
    - /
    - /health
    - /prove
