cvm-version: 0.11.1
cpus: 2
memory: 2048

# Measured into the enclave attestation.
vault-url: https://keys.tanyaverma.sh:9443

networks:
  web:

containers:
  - name: "demo"
    image: "ghcr.io/tinfoilsh/confidential-secrets-demo@sha256:0d6277c7b49cb20d183fa5b54e6af378c3cc77a88cc19df3be7e796f875241ed" # v0.0.4
    restart: always
    networks: [web]
    secrets:
      - DEMO_SECRET

shim:
  listen-port: 443
  upstream-port: 8080
  paths:
    - /
    - /health
    - /prove
